//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1460650_.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.ctdonhangs = new HashSet<ctdonhang>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> NhaSX { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdonhang> ctdonhangs { get; set; }
        public virtual loaisp loaisp { get; set; }
        public virtual nhasx nhasx1 { get; set; }
    }
}
